### PR TITLE
README files updated, generic lambda example

### PR DESCRIPTION
**Pull request by hmlearning**
PR for 2 commits.

### CODE REVIEW

**Review by astrophenomenon — APPROVED** [review]
Good examples of generic lambda

**Review by th4inquiry — APPROVED** [review]
Nice work! I'm impressed from your code that the abundant usage of auto type is very powerful to readability and effectiveness.

**Comment by hmlearning** [comment]
Thank you, everyone.

**Review by BMPark-Lab — APPROVED** [review]
nice job~

**Comment by hmlearning** [comment]
> nice job~

Thanks

**Pull request merged**
